### ISSUE TITLE
Flexing Images in `.fire1`

### ISSUE THREAD

**Issue by TheBrockEllis** [dustejo/Pokemon-Card#1]
https://github.com/dustejo/Pokemon-Card/blob/d41472a8d8a29d8be4077b54523b028658cc2b47/pokemoncard.html#L54

It looks like the CSS selector here is trying to grab all of the class of `fire_icon` that also has the class of `png`. I think the selector on that line should be `.fire1`. That selector is going to grab the left most side of the bottom1 section, and if you flex it, you can control how those 4 icons inside of it are laid out.

```css
.fire1 {
  display: flex;
}

.fire1 img {
  width: 50%;
}
```
